# Generated by Django 2.1.7 on 2019-07-18 05:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('short_title', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255, null=True)),
                ('last_updated', models.DateField(default=datetime.datetime.today)),
                ('total_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('debate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Debate')),
                ('rebuttals', models.ManyToManyField(null=True, to='rest_api.Point')),
            ],
        ),
        migrations.CreateModel(
            name='PointHyperlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substring', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Point')),
            ],
        ),
        migrations.CreateModel(
            name='PointImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, null=True)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Point')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_percentage', models.IntegerField(default=0)),
                ('debate', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Debate')),
                ('seen_points', models.ManyToManyField(to='rest_api.Point')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Starred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starred_list', models.ManyToManyField(to='rest_api.Debate')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
