# Generated by Django 2.1.7 on 2019-07-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='rebuttals',
            field=models.ManyToManyField(to='rest_api.Point'),
        ),
    ]
