# Generated by Django 2.2.5 on 2019-10-30 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointImage',
        ),
    ]
