# Generated by Django 2.1.7 on 2019-03-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.CharField(max_length=255)),
                ('debate_title', models.CharField(max_length=255)),
                ('debate_point', models.CharField(max_length=255)),
            ],
        ),
    ]
