# Generated by Django 2.1.7 on 2019-03-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debates',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
