# Generated by Django 2.1.7 on 2019-03-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='user_ID',
            field=models.IntegerField(),
        ),
    ]
