# Generated by Django 2.1.7 on 2019-07-18 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20190718_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='debate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Debate'),
        ),
    ]
