# Generated by Django 2.2.5 on 2019-11-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20191109_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='completed_percentage',
        ),
    ]
