# Generated by Django 2.1.7 on 2019-03-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20190317_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debates',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
