# Generated by Django 2.2.5 on 2019-11-10 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_remove_progress_completed_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='total_points',
        ),
    ]
