# Generated by Django 2.1.7 on 2019-03-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_passwordchange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordChange',
        ),
    ]
