# Generated by Django 2.1.7 on 2019-03-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20190317_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinglist',
            name='reading_list',
        ),
        migrations.AddField(
            model_name='readinglist',
            name='reading_list',
            field=models.ManyToManyField(to='rest_api.Debates'),
        ),
    ]
