# Generated by Django 2.1.7 on 2019-03-17 06:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_api', '0005_auto_20190317_0554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadingList',
            new_name='Starred',
        ),
        migrations.RenameField(
            model_name='starred',
            old_name='reading_list',
            new_name='starred_list',
        ),
    ]
