# Generated by Django 2.1.7 on 2019-03-16 20:18

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import rest_api.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_api', '0005_delete_passwordchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='debate_point',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='user_ID',
        ),
        migrations.AddField(
            model_name='progress',
            name='seen_points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=rest_api.models.get_default_data_array, size=None),
        ),
        migrations.AddField(
            model_name='progress',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
