# Generated by Django 2.2.5 on 2019-12-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_remove_debate_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='point',
            name='short_description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pointhyperlink',
            name='substring',
            field=models.TextField(max_length=255),
        ),
    ]
