# Generated by Django 2.1.7 on 2019-03-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_auto_20190317_0620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Debates',
            new_name='Debate',
        ),
    ]
