# Generated by Django 2.2.5 on 2019-12-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_auto_20191201_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='point',
            name='short_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pointhyperlink',
            name='substring',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pointhyperlink',
            name='url',
            field=models.URLField(),
        ),
    ]
