# Generated by Django 2.2.5 on 2019-12-01 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_auto_20191201_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointhyperlink',
            name='url',
            field=models.URLField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
