# Generated by Django 2.1.7 on 2019-06-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_auto_20190317_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
