# Generated by Django 2.2.5 on 2019-12-02 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_auto_20191201_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='time_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='debate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
