# Generated by Django 2.1.7 on 2019-06-05 16:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_debate_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='starred',
            name='starred_list_pk_batch',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=None),
        ),
    ]
