# Generated by Django 2.2.5 on 2019-12-02 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_auto_20191202_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='debate',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='time_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
