# Generated by Django 3.0.1 on 2020-01-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0011_auto_20191202_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='point',
            name='side',
            field=models.CharField(choices=[('pro', ''), ('con', ''), ('context', '')], max_length=255),
        ),
    ]
