# Generated by Django 2.1.7 on 2019-06-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0011_starred_starred_list_pk_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starred',
            name='starred_list_pk_batch',
        ),
    ]
