# Generated by Django 2.1.7 on 2019-06-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0012_remove_starred_starred_list_pk_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='short_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
