# Generated by Django 3.0.1 on 2020-01-11 07:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0013_auto_20200111_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='all_points_primary_keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(default=0), default=list, size=None),
        ),
    ]
