# Generated by Django 2.1.7 on 2019-06-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0013_debate_short_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='completed',
        ),
        migrations.AddField(
            model_name='progress',
            name='completed_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
