# Generated by Django 2.1.7 on 2019-07-13 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0014_auto_20190610_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PointHyperlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substring', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Point')),
            ],
        ),
        migrations.CreateModel(
            name='PointImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Point')),
            ],
        ),
        migrations.RemoveField(
            model_name='debate',
            name='debate_map',
        ),
        migrations.AddField(
            model_name='point',
            name='debate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Debate'),
        ),
        migrations.AddField(
            model_name='point',
            name='rebuttals',
            field=models.ManyToManyField(to='rest_api.Point'),
        ),
    ]
