# Generated by Django 3.0.1 on 2020-01-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0014_auto_20200111_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
