# Generated by Django 2.1.7 on 2019-07-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0017_auto_20190713_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='point',
            name='rebuttals',
            field=models.ManyToManyField(blank=True, to='rest_api.Point'),
        ),
        migrations.AlterField(
            model_name='pointimage',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
