# Generated by Django 2.1.7 on 2019-07-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0018_auto_20190715_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='short_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='debate',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pointimage',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
